
# default search alias
default_search_alias: default_search

# genome features index name
genome_features_current_index_name: genome_features

# Mapping of KBase type names to index names
ws_type_to_indexes:
  KBaseNarrative.Narrative: narrative
  KBaseFile.PairedEndLibrary: reads
  KBaseFile.SingleEndLibrary: reads
  KBaseGenomesAnnotations.Assembly: assembly
  KBaseGenomes.Genome: genome
  KbaseGenomes.Pangenome: pangenome
  KBaseGenomeAnnotations.Taxon: taxon
  KBaseTrees.Tree: tree
  KBaseMatrices.AttributeMapping: attribute_mapping
  KBaseMatrices.MetaboliteMatrix: matrix
  KBaseMatrices.DifferentialExpressionMatrix: matrix
  KBaseMatrices.ExpressionMatrix: matrix
  KBaseMatrices.FitnessMatrix: matrix
  KBaseMatrices.TraitMatrix: matrix
  KBaseSets.GenomeSet: genomeset
  KBaseMetagenomes.AnnotatedMetagenomeAssembly: annotated_metagenome_assembly

es_type_global_name: data

# SDK apps used for indexing, map from type_module.type_name -> {'sdk_func': _, 'sdk_app': _, 'sdk_version': _}
sdk_indexer_apps:
  KBaseMatrices.MetaboliteMatrix:
    sdk_app: kbasematrices_indexer
    sdk_func: run_kbasematrices_indexer
    sub_obj_index: attribute_mapping
  KBaseMatrices.DifferentialExpressionMatrix:
    sdk_app: kbasematrices_indexer
    sdk_func: run_kbasematrices_indexer
    sub_obj_index: attribute_mapping
  KBaseMatrices.ExpressionMatrix:
    sdk_app: kbasematrices_indexer
    sdk_func: run_kbasematrices_indexer
    sub_obj_index: attribute_mapping
  KBaseMatrices.FitnessMatrix:
    sdk_app: kbasematrices_indexer
    sdk_func: run_kbasematrices_indexer
    sub_obj_index: attribute_mapping
  KBaseMatrices.TraitMatrix:
    sdk_app: kbasematrices_indexer
    sdk_func: run_kbasematrices_indexer
    sub_obj_index: attribute_mapping
  KBaseSets.GenomeSet:
    sdk_app: genomeset_indexer
    sdk_func: run_genomeset_indexer

# Which indexes are considered "subobjects" (nested under workspace objects, such as genome features)
ws_subobjects:
  - "genome_features:2"
  - "pangenome_orthologfamily:1"
  - "attribute_mapping:1"
  - "annotated_metagenome_assembly_features:1"
  - "annotated_metagenome_assembly_features_version:1"

# Generic, global type mappings. These can be reused in any index mappings below.
global_mappings:
  ws_auth:
    access_group: {type: integer}
    is_public: {type: boolean}
  ws_object:
    timestamp: {type: date}
    obj_name: {type: keyword}
    creation_date: {type: date}
    shared_users: {type: keyword}
    creator: {type: keyword}
    version: {type: integer}
    obj_id: {type: integer}
    copied: {type: keyword}
    tags: {type: keyword}
    obj_type_version: {type: keyword}
    obj_type_module: {type: keyword}
    obj_type_name: {type: keyword}
  ws_subobject:
    parent_id: {type: keyword}

# For each untyped index alias, what are the index names for the latest versions of each?
latest_versions:
  narrative: "narrative:1"
  reads: "reads:1"
  assembly: "assembly:1"
  genome: "genome:1"
  genome_features: "genome_features:2"
  pangenome: "pangenome:1"
  pangenome_orthologfamily: "pangenome_orthologfamily:1"
  taxon: "taxon:1"
  tree: "tree:1"
  matrix: "matrix:1"
  attribute_mapping: "attribute_mapping:1"
  genomeset: "genomeset:1"
  indexing_errors: "indexing_errors:1"
  annotated_metagenome_assembly: "annotated_metagenome_assembly:1"
  annotated_metagenome_assembly_features: "annotated_metagenome_assembly_features:1"
  annotated_metagenome_assembly_version: "annotated_metagenome_assembly_version:1"
  annotated_metagenome_assembly_features_version: "annotated_metagenome_assembly_features_version:1"


# map from alias to contained indices
aliases:
  default_search:
    - "narrative:1"
    - "reads:1"
    - "assembly:1"
    - "genome:1"
    - "pangenome:1"
    - "pangenome_orthologfamily:1"
    - "taxon:1"
    - "tree:1"
    - "matrix:1"
    - "genomeset:1"
    - "indexing_errors:1"
    - "annotated_metagenome_assembly:1"
  default_search_subobjects:
    - "narrative:1"
    - "reads:1"
    - "assembly:1"
    - "genome:1"
    - "pangenome:1"
    - "pangenome_orthologfamily:1"
    - "taxon:1"
    - "tree:1"
    - "matrix:1"
    - "attribute_mapping:1"
    - "genomeset:1"
    - "indexing_errors:1"
    - "annotated_metagenome_assembly:1"
    - "annotated_metagenome_assembly_features:1"
    # here are the subobjects
    - "attribute_mapping:1"
    - "genome_features:2"
    - "pangenome_orthologfamily:1"
    - "annotated_metagenome_assembly_features:1"
  narrative:
    - "narrative:1"
  reads:
    - "reads:1"
  assembly:
    - "assembly:1"
  genome:
    - "genome:1"
  genome_features:
    - "genome_features:2"
  pangenome:
    - "pangenome:1"
  pangenome_orthologfamily:
    - "pangenome_orthologfamily:1"
  taxon:
    - "taxon:1"
  tree:
    - "tree:1"
  matrix:
    - "matrix:1"
  attribute_mapping:
    - "attribute_mapping:1"
  genomeset:
    - "genomeset:1"
  indexing_errors:
    - "indexing_errors:1"
  annotated_metagenome_assembly:
    - "annotated_metagenome_assembly:1"
  annotated_metagenome_assembly_features:
    - "annotated_metagenome_assembly_features:1"
  annotated_metagenome_assembly_version:
    - "annotated_metagenome_assembly_version:1"
  annotated_metagenome_assembly_features_version:
    - "annotated_metagenome_assembly_features_version:1"


# All ES type mappings
mappings:

  "narrative:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      narrative_title: {type: text}
      data_objects:
        type: nested
        properties:
          name: {type: keyword}
          obj_type: {type: keyword}
      cells:
        type: object
        properties:
          desc: {type: text}
          cell_type: {type: keyword}
      total_cells: {type: short}

  "reads:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      sequencing_tech: {type: keyword}
      size: {type: integer}
      interleaved: {type: boolean}
      single_genome: {type: boolean}
      provenance_services: {type: keyword}
      phred_type: {type: text}
      gc_content: {type: float}
      mean_quality_score: {type: float}
      mean_read_length: {type: float}

  "assembly:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      assembly_name: {type: keyword}
      mean_contig_length: {type: float}
      percent_complete_contigs: {type: float}
      percent_circle_contigs: {type: float}
      assembly_id: {type: keyword}
      gc_content: {type: float}
      size: {type: integer}
      num_contigs: {type: integer}
      taxon_ref: {type: keyword}
      external_origination_date: {type: keyword}  # should maybe be of type date?
      external_source_id: {type: keyword}
      external_source: {type: keyword}

  "genome:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      genome_id: {type: keyword}
      scientific_name: {type: keyword}
      size: {type: integer}
      num_contigs: {type: integer}
      genome_type: {type: keyword}
      gc_content: {type: float}
      taxonomy: {type: keyword}
      mean_contig_length: {type: float}
      external_origination_date: {type: keyword}  # should maybe be of type date?
      original_source_file_name: {type: keyword}
      # new fields to include:
      cds_count: {type: integer}
      feature_count: {type: integer}
      mrna_count: {type: integer}
      non_coding_feature_count: {type: integer}
      assembly_ref: {type: keyword}
      source_id: {type: keyword}
      feature_counts: {type: object}
      source: {type: keyword}
      warnings: {type: text}

  "genome_features:2":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      id: {type: keyword}
      genome_scientific_name: {type: keyword}
      feature_type: {type: keyword}
      functions: {type: keyword}
      contig_ids: {type: keyword}
      sequence_length: {type: integer}
      genome_version: {type: integer}
      assembly_ref: {type: keyword}
      genome_feature_type: {type: keyword}
      starts: {type: integer}
      strands: {type: keyword}
      stops: {type: integer}
      aliases: {type: keyword}

  "pangenome:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      pangenome_id: {type: keyword}
      pangenome_name: {type: keyword}
      pangenome_type: {type: keyword}
      genome_upas: {type: keyword}

  "pangenome_orthologfamily:1":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      ortholog_id: {type: keyword}
      ortholog_type: {type: keyword}
      function: {type: keyword}
      gene_ids: {type: keyword}

  "taxon:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      scientific_name: {type: keyword}
      scientific_lineage: {type: keyword}
      domain: {type: keyword}
      kingdom: {type: keyword}
      parent_taxon_ref: {type: keyword}
      genetic_code: {type: integer}
      aliases: {type: keyword}

  "tree:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      tree_name: {type: keyword}
      type: {type: keyword}
      labels:
        type: nested
        properties:
          node_id: {type: text}
          label: {type: text}

  "attribute_mapping:1":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      attributes: {type: keyword}
      attribute_ontology_ids: {type: keyword}
      attribute_units: {type: keyword}
      attribute_unit_ontology_ids: {type: keyword}
      attribute_values: {type: keyword}
      attribute_value_ontology_ids: {type: keyword}
      instances: {type: object}
      num_attributes: {type: integer}
      num_instances: {type: integer}

  "matrix:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      matrix_type: {type: keyword}
      row_attributes: {type: keyword}
      col_attributes: {type: keyword}
      row_attribute_ontology_ids: {type: keyword}
      col_attribute_ontology_ids: {type: keyword}
      row_attribute_values: {type: keyword}
      col_attribute_values: {type: keyword}
      row_ids: {type: keyword}
      col_ids: {type: keyword}
      num_rows: {type: integer}
      num_columns: {type: integer}
      attributes: {type: keyword}

  "genomeset:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      genomes:
        type: object
        properties:
          genome_ref: {type: keyword}
          label: {type: keyword}
      description: {type: text}

  "annotated_metagenome_assembly:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: integer}
      source_id: {type: keyword}
      source: {type: keyword}
      gc_content: {type: float}
      warnings: {type: keyword}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword}
      publication_titles: {type: keyword}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text}

  "annotated_metagenome_assembly_features:1":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      id: {type: keyword}
      type: {type: keyword}
      size: {type: integer}
      contig_ids: {type: keyword}
      starts: {type: integer}
      strands: {type: keyword}
      stops: {type: integer}
      functions: {type: keyword}
      functional_descriptions: {type: keyword}
      warnings: {type: keyword}
      parent_gene: {type: keyword}
      inference_data: {type: keyword}
      dna_sequence: {type: text}
      gc_content: {type: float}
      annotated_metagenome_assembly_size: {type: integer}
      annotated_metagenome_assembly_num_features: {type: integer}
      annotated_metagenome_assembly_num_contigs: {type: integer}
      annotated_metagenome_assembly_gc_content: {type: float}

  "annotated_metagenome_assembly_version:1":
    global_mappings: [ws_auth, ws_object]
    properties:
      size: {type: integer}
      source_id: {type: keyword}
      source: {type: keyword}
      gc_content: {type: float}
      warnings: {type: keyword}
      num_contigs: {type: integer}
      mean_contig_length: {type: float}
      external_source_origination_date: {type: keyword}
      original_source_file_name: {type: keyword}
      environment: {type: keyword}
      num_features: {type: integer}
      publication_authors: {type: keyword}
      publication_titles: {type: keyword}
      molecule_type: {type: keyword}
      assembly_ref: {type: keyword}
      notes: {type: text}

  "annotated_metagenome_assembly_features_version:1":
    global_mappings: [ws_subobject, ws_auth, ws_object]
    properties:
      id: {type: keyword}
      type: {type: keyword}
      size: {type: integer}
      contig_ids: {type: keyword}
      starts: {type: integer}
      strands: {type: keyword}
      stops: {type: integer}
      functions: {type: keyword}
      functional_descriptions: {type: keyword}
      warnings: {type: keyword}
      parent_gene: {type: keyword}
      inference_data: {type: keyword}
      dna_sequence: {type: text}
      gc_content: {type: float}
      annotated_metagenome_assembly_size: {type: integer}
      annotated_metagenome_assembly_num_features: {type: integer}
      annotated_metagenome_assembly_num_contigs: {type: integer}
      annotated_metagenome_assembly_gc_content: {type: float}

  "indexing_errors:1":
    properties:
      evtype: {type: keyword}
      wsid: {type: integer}
      objid: {type: integer}
      error: {type: text}
